# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 398198973dce51d99b167c432f29650a45d17c1232bc8aea47a7dbef576152ee86060952ab4e3cb981311e34907d8c55dc0264b2b7c0b9567511cc4c1b23869e

test:
  secret_key_base: bebafbf0aac4e2bbe04d04517d08fd293eb9c11b46428c4306ea0e4d1dc7d57ef4671c284ffe73f293f459984fbc3ceb6d2121fe2adcc214544590bab5ef5820

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
